ALTER TABLE "TokenMarketSnapshot"
ADD COLUMN "priceChange1h" DOUBLE PRECISION,
ADD COLUMN "priceChange24h" DOUBLE PRECISION,
ADD COLUMN "volume24h" DOUBLE PRECISION,
ADD COLUMN "liquidityUsd" DOUBLE PRECISION,
ADD COLUMN "marketDataSource" TEXT;
